# Generated by Django 4.2.5 on 2023-09-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id_filme', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
            ],
        ),
    ]
