# Generated by Django 4.2.5 on 2023-09-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_recommender', '0003_remove_respostausuario_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespostasUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_resposta', models.DateTimeField(auto_now_add=True)),
                ('recomendacao_filme', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='RespostaUsuario',
        ),
    ]
