# Generated by Django 4.2.5 on 2023-09-30 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_recommender', '0004_respostasusuario_delete_respostausuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respostasusuario',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
