# Generated by Django 4.2.5 on 2023-10-10 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_recommender', '0008_alter_respostasusuario_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respostasusuario',
            old_name='ator_atriz_favorito',
            new_name='pergunta1',
        ),
        migrations.RenameField(
            model_name='respostasusuario',
            old_name='diretor_favorito',
            new_name='pergunta10',
        ),
        migrations.RenameField(
            model_name='respostasusuario',
            old_name='final_emocionante_preferido',
            new_name='pergunta2',
        ),
        migrations.RenameField(
            model_name='respostasusuario',
            old_name='genero_filme_preferido',
            new_name='pergunta3',
        ),
        migrations.RenameField(
            model_name='respostasusuario',
            old_name='gosto_filmes_acao_adrenalina',
            new_name='pergunta4',
        ),
        migrations.RenameField(
            model_name='respostasusuario',
            old_name='preferencia_filmes_contemporaneos',
            new_name='pergunta5',
        ),
        migrations.RenameField(
            model_name='respostasusuario',
            old_name='preferencia_filmes_fatos_reais_ficcao',
            new_name='pergunta6',
        ),
        migrations.RenameField(
            model_name='respostasusuario',
            old_name='protagonista_preferido',
            new_name='pergunta7',
        ),
        migrations.RenameField(
            model_name='respostasusuario',
            old_name='sentimento_filmes_comedia_romantica',
            new_name='pergunta8',
        ),
        migrations.RenameField(
            model_name='respostasusuario',
            old_name='sentimento_filmes_terror',
            new_name='pergunta9',
        ),
    ]
