# Generated by Django 4.2.5 on 2023-10-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_recommender', '0009_rename_ator_atriz_favorito_respostasusuario_pergunta1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmePesquisado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_filme', models.CharField(max_length=255)),
                ('data_pesquisa', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
